### PR TITLE
raidboss: M4S adjust Tail Thrust callouts

### PR DESCRIPTION
**Pull request by xiashtra**
While testing #458, I noticed that TTS really doesn't like when we use `==>` or `<==` in triggers (it causes unexpected TTS output).

### CODE REVIEW

**Comment by JLGarber** [comment]
Given the discussion about arrows on #458, is it maybe worth adjusting this to put the arrows for the knockback version of Tail Thrust on the ends of their respective strings, since we aren't using it to indicate "then" here either?

**Comment by wexxlee** [comment]
> Given the discussion about arrows on #458, is it maybe worth adjusting this to put the arrows for the knockback version of Tail Thrust on the ends of their respective strings, since we aren't using it to indicate "then" here either?

Definitely should go at the beginning/end of the string.  Right now, tts will speak `Double Knockback (<= Start on Left)` as `double knockback less than equals start on left`.

And doing #465 should take care of the `=>` vs `==>` issue.

**Comment by xiashtra** [comment]
Adjusted arrow placement to the beginning/end of the output lines.

**Review by wexxlee — APPROVED** [review]
LGTM.  Per discord discussion: I think it makes sense in this case to reorder the non-`en` strings rather than blowing them all away. If it causes translation weirdness in any of the supported langs, it's hopefully less burdensome to have a PR or two to fix it than to require five PRs to re-add.

**Pull request merged**
