### PR TITLE
raidboss: Add r1n mouser trigger

### PR DESCRIPTION
**Pull request by valarnin**
If #272 is agreed upon and lands before this, I'll update.

The duration could be handled better by determining how many telegraph sets have happened so far and adjusting based on that, but this timing seemed to be okay enough for me when doing in-zone testing.

### CODE REVIEW

**Review by wexxlee — COMMENTED** [review]
Hmm, I'm getting somewhat inconsistent output from this.  On the first Mouser, for example, I just get a single tile call, e.g. `SE` (which is confusing since SE does get hit), but on the second Mouser, I get a single call, followed a few seconds later by a triple call (e.g. `SE` first, followed by `SW => SE => SE`), which is a little confusing.

I think this could possibly be simplified, since there's only two possibilities regardless of the patterns.  The player can always start SW, then move SE as soon as the SE title gets hit.  Then: (1) either the player remains SE (because SW gets hit a second time), or (2) they swap back to SW because SE will get hit a second time.  So I think the trigger could probably just be reduced to two fixed outputs, e.g.:
`SW => SE (Then Stay)` or `SW => SE => SW (Swap Twice)` (or something to that effect).

And the trigger can simply look at whether `09` or `0A` takes the second hit to determine which output to give.

**Comment by valarnin** [comment]
Hmm, I could have sworn that the first safe spot wasn't always SW, but that might have been bad info from when I had the MapEffect squares mismapped (I accidentally mapped the x and y coordinates backwards at first).

This adjustment to logic and text makes sense, I'll get it in later today when I get a chance to go back in and test the changes.

**Comment by xiashtra** [comment]
> Hmm, I could have sworn that the first safe spot wasn't always SW, but that might have been bad info from when I had the MapEffect squares mismapped (I accidentally mapped the x and y coordinates backwards at first).
> 
> This adjustment to logic and text makes sense, I'll get it in later today when I get a chance to go back in and test the changes.

I think the Savage trigger output should get changed too for consistency since it's the same logic/movement.

**Review by wexxlee — APPROVED** [review]
Probably some additional cleanup could be done to match the scrub you gave the savage trigger, but I think this is also fine to merge as-is.

**Pull request merged**
