### PR TITLE
raidboss: The Gilded Araya timeline

### PR DESCRIPTION
**Pull request by JLGarber**
Thanks so much wexxlee for getting the triggers in place so quickly!

I was lucky enough to get a 9-minute pull in-game and the timeline seemed okay. Please do check that I haven't misplaced any abilities when accounting for multiple possibilities in a given line. Overall I feel good about this after seeing it in-game, but it's very likely I've missed something.

cc @wexxlee @valarnin

### CODE REVIEW

**Comment by valarnin** [comment]
The only thing that jumps out to me immediately as a point to review/explain is the excessively large sync windows on some of the abilities.

**Comment by JLGarber** [comment]
Good point. That's a personal thing I generally do to future-proof timelines that might have skips that aren't encountered on content. It costs us nothing to add "safety syncs" and if it means we avoid annoyances in 7.X and beyond, I think it's worth it. I'll add a note.

**Comment by valarnin** [comment]
I think it's a bit risky from a maintainability perspective. Consider the potential landmine that is these two lines:
```
97.2 "Iconography: Pedestal Purge" Ability { id: "8C81", source: "Asura" } window 100,10
248.1 "Iconography: Pedestal Purge/Wheel Of Deincarnation/Bladewise 1" Ability { id: ["8C81", "8CB3", "8C85"], source: "Asura" } window 100,10
```

If the `248.1` line were to ever have its sync window expanded to overlap the `97.2` line, that's going to cause issues, for example.

I think it's fine to future proof where possible, I'm just not sure how I feel about these specifically due to that. Maybe a comment makes sense, or some sort of general comment or note that the timings shouldn't be adjusted to overlap or something. Mostly I'm just wanting to make sure that it's considered before merging.

**Comment by JLGarber** [comment]
I see what you're saying, but I *think* I've accounted for that. Even assuming the latest possible sync on the early line and the earliest possible sync on the later line, there isn't an overlap. This should be true for all possible conflict points. (If I've missed one, I'll definitely fix that.)

Do we maybe also want to just set the lookbefore window to 50 on the repeated abilities later in the encounter? That is, in the second line you mentioned, (and others like it later,) change the window to 50,10 from the 100,10 it currently is?

**Comment by valarnin** [comment]
After letting this simmer for a bit, I think my main takeaway is that we should probably limit big `window`s to only potentially phasing timeline entries, and that there should only be one big `window` per ability ID. That should provide sufficient future proofing without leaving potential landmines for us to step on as well.

By "big `window`s", I'm referring to anything more than 25 seconds.

In the case of this timeline, I think it makes sense to remove or alter the following entries:

- 151.5 - Khadga - I find it exceedingly unlikely that this would be a potential phase push point. It's more likely that any phase push would phase to the beginning of the loop or to the end of the loop where "Many Faces" is handled.
- 248.1 - Iconograhpy - I think it makes more sense for a jump-to-start-of-loop to be on the "Divine Awakening" just above at 238.4
- 461.9 - Divine Awakening - I think I'd rather the "Divine Awakening" at 238.4 cover the entirety of the loop except the end, with a comment indicating as such

(This is all subjective opinion, please push back if something doesn't make sense or you don't agree. I'm still trying to find an equilibrium on how much feedback I should provide now that quisquous is no longer around, especially because I traditionally didn't PR cactbot code and only handled a few sets of timelines and triggers, so please let me know if I'm doing something incorrect here)

**Comment by wexxlee** [comment]
Looks good to me.  Tested in-game and works as expected.  Thanks for the collab on this!

I don't have a strong opinion on the current discussion, but fwiw:
> * 151.5 - Khadga - I find it exceedingly unlikely that this would be a potential phase push point. It's more likely that any phase push would phase to the beginning of the loop or to the end of the loop where "Many Faces" is handled.

I agree, it's probably unlikely there would be a phase push directly to Khadga. The first 3 Iconic Executions occur in a fixed order, and from a design perspective, it would be weird to skip over all/part of those only to then start the "jumping Khadga" later, since they're sort of explanatory mechanics.

**Comment by JLGarber** [comment]
To address your last paragraph first, don't worry about it. What you did or did not do before while quisquous was still available shouldn't be seen as something to limit what you say here. Obviously of the active maintainers I'm the most knowledgeable on how timelines and triggers "should" function, but understanding that, I don't want to push my ideas over others'. (Quisquous, correctly, was opinionated at points because this was their project, but that's not for me.)

All that is to say, please err on the side of more rather than less, so long as it's not a burden for you. I can leave aside anything that's "really wrong", but I don't expect that to happen much. A lot of what I do with timelines ends up being more art than science, ironic as that may be. Having a "less knowledge, more abstract technical details" view is very helpful for the long-term health of the project.

As for the specific suggestions, yeah, from those perspectives that all makes sense. I'll make those changes and we can approve from there.

**Review by wexxlee — APPROVED** [review]

**Pull request merged**
