### PR TITLE
raidboss: r3s Barbarous Barrage Uptime Knockback

### PR DESCRIPTION
**Pull request by Legends0**
The first tower is generally the hardest to get the angles correct due to the greatest distance of the knockback and closeness to the center of the knockback origin. The first tower dodge is also most significant for melee uptime. This trigger defaults to dodging the first two towers.

A 15s delay will dodge all three towers. This is very tight and if missing the first tower, it will almost guarantee missing the next two towers. A 12s delay dodges the first two towers. This is lenient, but too late and you likely will end up with a damage down from Murderous Mist. A 9s delay will dodge only the first tower. Lateness on this could more easily lead to a death or missed tower due to angle of knockback.

Since missed tower soaks result in a stacking raidwide DoT debuff. I think defaulting to 12s is the safest as it seems most likely to recover.

Any tower explosions that are dodged require moving to the next tower. Sprint is unnecessary for first two, but may be helpful for longer casts. If the middle tower is dodged, you likely need some sort of jump/teleport ability to avoid getting hit by murderous mist as you only have 2s to get in position rather than the 3s between tower explosions.

Another thing to note, the explosion knockback happens before the tower animation disappears, and so players would need to still learn the timing when using this strategy since they should move before the tower disappears for more time to move to the next tower. A move trigger could be beneficial for this, but could unnecessarily add noise.

There was discussion over whether this should be a user trigger or not. It may take on in PF as it grants melee uptime, and removes a tight position requirement for the first tower without too strict of timing.

### CODE REVIEW

**Comment by xiashtra** [comment]
> There was discussion over whether this should be a user trigger or not. It may take on in PF as it grants melee uptime, and removes a tight position requirement for the first tower without too strict of timing.

I feel that this should be an optional trigger using the existing trigger config support.  I haven't seen any PF groups using knockback prevent for these towers on NA so far.

**Comment by Legends0** [comment]
> > There was discussion over whether this should be a user trigger or not. It may take on in PF as it grants melee uptime, and removes a tight position requirement for the first tower without too strict of timing.
> 
> I feel that this should be an optional trigger using the existing trigger config support. I haven't seen any PF groups using knockback prevent for these towers on NA so far.

Sounds good, easy to have another pr to remove the disabled by default if it gains popularity later.

**Comment by xiashtra** [comment]
I was thinking if you did something like this https://github.com/OverlayPlugin/cactbot/blob/65daa5421f02ec4ab16fd8c23517a95139aefa43/ui/raidboss/data/06-ew/raid/p12s.ts#L512-L539 we could add a comment explaining the timing of the callout.

**Comment by Legends0** [comment]
> we could add a comment explaining the timing of the callout that would appear in the user-facing configuration page.

I forgot that existed now. I implemented an example. Wording to be determined. I won't get around to testing with this configuration this week.

**Review by wexxlee — APPROVED** [review]
Sorry for the super-log delay in getting around to this.  The config UI stuff looks good, and the trigger fires as expected with logs.  I'm not using this particular strat so I can't really offer a substantive opinion on timing, but if it feels right to you, I think it's fine to merge as it can always be adjusted later if needed.

**Pull request merged**
