### PR TITLE
resources: add no mercy in effect id

### LINKED ISSUE #280: Why was `resources/effect_id.ts` significantly modified in the commit `resources:ko 6.35`?
### What's your question?

When I was developing the relevant plugin, I found that `resources/effect_id.ts` was significantly modified in https://github.com/OverlayPlugin/cactbot/commit/6c3dbeff549da5203cb5bb12987ddd8df6a59b91 

**Resulting in the deletion of codes such as `'NoMercy': '727'`, etc.**

The title of this code commit is `resources: ko 6.35`.  And I don't know why `effect_id.ts` was significantly modified?

Is this a bug or not?

image

### PR DESCRIPTION
**Pull request by MaikoTan**
Just a temporarily solution

Fix #280

### CODE REVIEW

**Review by Echoring — APPROVED** [review]

**Comment by valarnin** [comment]
`No Mercy` wasn't the only effect ID impacted, it was just the easiest one to spot check. Looking through just the referenced commit in the linked issue shows WHM's `Aquaveil`, DRK's `Dark Arts`, PLD's `Holy Sheltron`, AST's `Macrocosmos`, RDM's `Magick Barrier`, etc etc.

**Comment by Echoring** [comment]
> `No Mercy` wasn't the only effect ID impacted, it was just the easiest one to spot check. Looking through just the referenced commit in the linked issue shows WHM's `Aquaveil`, DRK's `Dark Arts`, PLD's `Holy Sheltron`, AST's `Macrocosmos`, RDM's `Magick Barrier`, etc etc.

I remembered, these are all PVP effects added in 6.1... don't know why changed in 6.35 though.

**Comment by valarnin** [comment]
> don't know why changed in 6.35 though.

Probably `gen_effect_id.ts` wasn't run for a while? I'm not sure either, without looking through all the commit logs.

**Comment by MaikoTan** [comment]
> Probably `gen_effect_id.ts` wasn't run for a while? I'm not sure either, without looking through all the commit logs.

Before that commit is https://github.com/OverlayPlugin/cactbot/commit/75ad0d762e2fae4710f9bc4a9734e19bd406be2f and https://github.com/OverlayPlugin/cactbot/commit/c4ec24f5c4c78f1aaa5233ded48fe638d1ba61be , both created by @Echoring , don't know if it is hand-made.

**Comment by Echoring** [comment]
> Before that commit is [75ad0d7](https://github.com/OverlayPlugin/cactbot/commit/75ad0d762e2fae4710f9bc4a9734e19bd406be2f) and [c4ec24f](https://github.com/OverlayPlugin/cactbot/commit/c4ec24f5c4c78f1aaa5233ded48fe638d1ba61be) , both created by @Echoring , don't know if it is hand-made.

Seems indeed manually added, for that time gen_effect_id.ts is temporarily broken.

**Pull request merged**
