### PR TITLE
raidboss: r4s electrope edge 2 improvements

### PR DESCRIPTION
**Pull request by wexxlee**
This adds some additional info to the callouts for EE2.  One strat involves switching partners based on long vs. short debuff assignment if it's Four Star + Sidewise Spark after; another strat involves fixed positions (and variable partners) based on role & Witchgleam stack count.  This supports both by:
 - Adding the list of other players with the same (short vs. long) debuff to the initial call, similiar to the snake callouts in p8s.
 - Adding `(X stacks after)` to the Star + Sidewise Spark alert for long debuffs.

### CODE REVIEW

**Comment by valarnin** [comment]
I don't think listing other player names on `R4S Electrical Condenser Debuff Initial` is needed.

The strat in Aether PF is fixed positions based on your role and your stack count, so just a reminder of your stack count on the sidewise spark count is sufficient.

For reference:

image

**Comment by wexxlee** [comment]
> I don't think listing other player names on `R4S Electrical Condenser Debuff Initial` is needed.

Respectfully, I think I disagree.  A number of the world prog groups were doing debuff role swaps so people had fixed positions, and I know a number of non-world prog groups still doing that.

If the (current) aether PF strat becomes universal (keeping in mind there's other DCs and regions that may adopt something different), the extra info from the initial call can always be removed. But I think it's useful for now for at least the way some groups are doing it.  I think our approach in the past has been to generally display info in a strat-agnostic fashion, and to support specific strats with config options.

**Comment by valarnin** [comment]
> Respectfully, I think I disagree. A number of the world prog groups were doing debuff role swaps so people had fixed positions, and I know a number of non-world prog groups still doing that.

I was referring to my original request for the reminder for stack counts for longs. If there's value here for other strats, I'm fine with adding the extra info. I just don't want to pass over the threshold of "too much info".

I'll go ahead and approve this, the code itself looks fine, my main concern was "this might be a lot to take in while also doing other mechs".

**Review by valarnin — APPROVED** [review]

**Comment by wexxlee** [comment]
> I was referring to my original request for the reminder for stack counts for longs. If there's value here for other strats, I'm fine with adding the extra info. I just don't want to pass over the threshold of "too much info".
> 
> I'll go ahead and approve this, the code itself looks fine, my main concern was "this might be a lot to take in while also doing other mechs".

I'm fine with forking the PR to add the long-stack reminder that you asked for, and we can continue to noodle on the names portion and get input from others.  There may be a more reasonable way to shorten it (just display name of role buddy with same length debuff?), or we can see how things unfold with strats in the coming weeks.  Either way, the long-stack reminder portion has utility beyond just a particular strat, so I'm fully aligned on landing that now.

**Comment by valarnin** [comment]
I'm fine with landing this as-is and putting up an issue or something for others to weigh in on if needed?

**Pull request merged**
