### PR TITLE
ci: update issue templates to use forms

### PR DESCRIPTION
**Pull request by wexxlee**
This updates the current issue templates to use GH forms syntax (and collects some additional info on bug reports that we've been asking submitters for).

AFAIK, there's no really good way to preview these forms from the raw yaml until it's merged, so I'm including some screenshots of what it will look like (apologies for the dark mode if that's not your thing 😶)

## Toplevel "Issues" page
forms_issuespage

## Bug Report form
forms_bug_1
forms_bug_2

## Question form
forms_question

## Feature Request form
forms_featurereq

### CODE REVIEW

**Review by valarnin — APPROVED** [review]
This looks good to me. I'd like to see confirmation from maybe @JLGarber as well, just in case I'm missing something obvious here.

**Comment by JLGarber** [comment]
This all looks fine to me. I very much appreciate the deliberate solicitation of the reporting user's configuration. Having that information up front More Of The Time should save everyone time and cut down on noise.

**Review by JLGarber — APPROVED** [review]

**Review by xiashtra — APPROVED** [review]
Looks good.  The "Common Issues and Workarounds" page is pretty extensive, so I would not be surprised if many users just click 'OK' on that checkbox without actually going through all the steps.  If that happens, we might consider adding a couple items from there as seperate checkboxes in the future ('enable injection' being a major one currently).

**Comment by wexxlee** [comment]
> [...] I would not be surprised if many users just click 'OK' on that checkbox without actually going through all the steps. If that happens, we might consider adding a couple items from there as seperate checkboxes in the future ('enable injection' being a major one currently).

Makes sense.  Yeah, the checkbox is really just a soft prod since that's all we can do, but I'd be in favor of adding additional/specific checkboxes down the road, particularly if we start to see a lot of support issues with same root cause/fix.

**Pull request merged**
