### PR TITLE
util: switch to xivapi beta

### PR DESCRIPTION
**Pull request by wexxlee**
This is an initial pass at updating the xivapi lib and the gen_* util scripts that use it to take advantage of the new xivapi beta API.  The line count is running a little high, but the vast majority of the changes are due to the API schema changes.  The only notable code refactoring is in `util/xivapi.ts`, and mostly relates to the way looping through result sets now has to be done due to the absence of pagination properties.

Running `npm run generate -- -f all` also updated some of the resource files.  The diff seems to be mostly new things added in 6.55, along with a small bug fix in the way that synthetic zone info is handled.  (NB: We can probably kill off the support for the pre-rework dungeons now that cn/ko is caught up, but I'd rather do that in a separate PR.)

~~Marking this as WIP for now so I can look with fresh eyes tomorrow and probably tidy a few more things up. But feedback welcome.~~ Should be ready for review.

### CODE REVIEW

**Review by valarnin — APPROVED** [review]
LGTM. Didn't get a chance to test this locally, though.

**Comment by wexxlee** [comment]
Jfyi to all, I'm intentionally holding off on merging this until xivapi beta has 7.0 data, in case there are schema changes or other things that require fixing (and there's also the off-chance that we get additional patch files in the next 12 hours - I think sqex did that with ShB?).  Once the api changes are-validated, I plan to merge this and separately PR the resource file updates.

**Comment by wexxlee** [comment]
> Jfyi to all, I'm intentionally holding off on merging this until xivapi beta has 7.0 data, in case there are schema changes or other things that require fixing (and there's also the off-chance that we get additional patch files in the next 12 hours - I think sqex did that with ShB?). Once the api changes are validated, I plan to merge this and separately PR the resource file updates.

I'm going to extend the pause on merging this.  The beta was significantly slower to update for Patch 7.0 (due to EXDSchema chnges).  While that might not always be the case going forward, and while the current xivapi will eventually be deprecated, I think it might be more prudent to see what happens with Patch 7.01/Patch 7.05 before deciding to switch over.

**Comment by wexxlee** [comment]
This has been rebased, and the `gen_zone_id_and_info` script was updated to reflect an exd schema change.  This now generates the same prod data as the original API (all scripts re-run to verify).  Just doing this pre-emptively before 7.01 in case the beta api is live first, so this can be merged and resource files updated more promptly.  Will continue to keep the PR on hold for now though.

**Comment by wexxlee** [comment]
> This has been rebased, and the `gen_zone_id_and_info` script was updated to reflect an exd schema change. This now generates the same prod data as the original API (all scripts re-run to verify). Just doing this pre-emptively before 7.01 in case the beta api is live first, so this can be merged and resource files updated more promptly. Will continue to keep the PR on hold for now though.

Beta updated first with fresh data, so this should be good to merge now.

**Pull request merged**
