### PR TITLE
ci: improve release workflow

### PR DESCRIPTION
**Pull request by wexxlee**
(edited after most recent commit)

When the project was moved to the OP repo, the `release.yml` workflow was updated so that releases are no longer published in draft state.  This means that releases happen automatically once a version-bump PR is merged; however, the release notes do not include any summary in the title (only a version number), and the release notes will be published instantly without edits.  While the release notes can always be manually edited by a contributor after the fact, I don't think that's ideal. 

This PR adds an npm script, `npm run release` that collects the version-bump type, a release summary, and whether the release should be in draft, and it stores that data and runs npm version to trigger a version bump PR (replacing the need to run `npm version`).  This also updates the `release.yml` workflow to collect these attributes and integrate them.

(Note: Because of the changes, merging this PR will trigger the release workflow, even though I'm not intending to actually trigger a release.  Because there's no version bump, however, the worklow will exit gracefully without doing a release.  I do plan to PR a version bump since it's been a month and there are some i18n/bugfix PRs that have been merged since.  But I'd prefer to land this first.)

### CODE REVIEW

**Comment by valarnin** [comment]
It seems a bit odd to parse this out of the .cs file instead of pulling it from package.json or something that has better native support for parsing?

**Comment by wexxlee** [comment]
> It seems a bit odd to parse this out of the .cs file instead of pulling it from package.json or something that has better native support for parsing?

My thinking there was that since `release.yml` pulls the version string from the .cs files and uses that for validating against the git tag and creating the GH release tag and attributes, that it made sense to keep these new fields in the same place and to use the existing pwsh logic to get the values.  We could use JSON stuff to write the attributes more cleanly when setting them, although I'd have to think if there's a non-regex way to grab them from within the build sandbox.  But, yeah, I don't feel strongly about it if you think package.json is better?

**Comment by valarnin** [comment]
I think because one of the long-term goals is to get rid of the actual C# plugin code here in favor of upstreaming what it's doing in a more generic format to OverlayPlugin, it doesn't make sense to have it in the .cs file. But if we're going to have to move that logic for determining version number again later anyways, I guess it doesn't matter if we put it there for now?

**Comment by wexxlee** [comment]
> I think because one of the long-term goals is to get rid of the actual C# plugin code here in favor of upstreaming what it's doing in a more generic format to OverlayPlugin, it doesn't make sense to have it in the .cs file. But if we're going to have to move that logic for determining version number again later anyways, I guess it doesn't matter if we put it there for now?

Ahh, okay, good to know - didn't realize the C# plugin code was on life support.  In that case, since I'm already tinkering with it, I might as well move the version number logic too and kill two birds.  The only tricky thing is that the release job only runs if there's a push to the AssemblyInfo.cs file, so I'll have to figure out the right way to run the job without that hook.  Let's leave this unmerged for now and I'll see what I can come up with.

**Comment by wexxlee** [comment]
The most recent commit moves the release attributes to `package.json` and removes all dependencies on `AssemblyInfo.cs` from the `release.yml` workflow.  Although this workflow will now be triggered whenever a change to `package.json` is pushed, it will also now exit gracefully without throwing an error (and without doing a release) if there's no version bump.

The last commit also consolidates the setting of the attributes and `npm version` into a single script, wrapped in an inquirer interface for ease (although it still accepts CLI arguments).  Doc updated accordingly.

**Review by valarnin — APPROVED** [review]
This looks good to me now. My only comment is that it looks like extra newlines were added to `release.yml`. Should we add linting/formatting settings (in a followup PR) for `.yml` files to enforce consistent formatting?

**Comment by wexxlee** [comment]
> This looks good to me now. My only comment is that it looks like extra newlines were added to `release.yml`. Should we add linting/formatting settings (in a followup PR) for `.yml` files to enforce consistent formatting?

Yeah, I think that's a good idea.  The newlines were inconsistent within `release.yml` before (they should at least be internally consistent now), but we should enforce consistency across them all.  I'll create an issue for this and add to my to-dos.

**Pull request merged**
