### PR TITLE
raidboss: Add missing properties from OverlayPlugin

### PR DESCRIPTION
**Pull request by valarnin**
These fields were added as part of https://github.com/OverlayPlugin/OverlayPlugin/pull/253 but weren't updated in cactbot.

If a trigger attempts to match against a field prior to these fields as well as a field after these fields (in my specific case, matching against both `BNpcID` and `PosX`/`Y`/`Z`), the constructed regex will fail as it does not allow for unknown fields to be matched against.

I don't think there's a way to allow unknown fields to be matched against while retaining any sort of performance, the built regex would be an absolute monster and would be incredibly slow.

### CODE REVIEW

**Review by JLGarber — APPROVED** [review]

**Review by wexxlee — APPROVED** [review]

**Review by xiashtra — APPROVED** [review]

**Comment by xiashtra** [comment]
Should we have a way to catch changes from OverlayPlugin and raise an issue here?  Is that feasible?  Is it infrequent enough not to worry about?

**Comment by valarnin** [comment]
> Should we have a way to catch changes from OverlayPlugin and raise an issue here? Is that feasible? Is it infrequent enough not to worry about?

I'm not sure there's an effective way to check for something like this. We'd have to somehow have an action here that triggers when an OP commit is merged, which I don't think exists?

**Comment by wexxlee** [comment]
> I'm not sure there's an effective way to check for something like this. We'd have to somehow have an action here that triggers when an OP commit is merged, which I don't think exists?

It's possible, but a little messy.  GH actions support a `cron` trigger (NB: runner availability can sometimes delay execution time by up to 15 mins, because GH.  Don't use if timing is actually important).

You'd basically have to have a custom script called by that workflow that would hit a REST API endpoint for the OP repo (probably `pulls` or `events`, filtered to PRs merged within the last X days).  [I also don't know whether this repo's `secrets.GH_TOKEN` has API read perms for all other repos in the org; if not, you'd have to create a PAT and add it to `secrets` - and since they expire, that's a maintenance thing.]

We'd probably only care about merges to one of the Network/Memory processor classes, so would want to filter on those.  I don't recall if the `events` endpoint lists changed files in the merge (pretty sure `pulls` does not), but it is possible to get a diff via the API to check file paths updated.

If a merge meeting those criteria is detected, we'd probably want to -- I guess, create an issue here to say "hey someone, go check this out".  (That's probably the easiest part - a bunch of existing workflow actions for that we can hook.)

So yeah, a bit messy.  But doable.

**Comment by xiashtra** [comment]
> > Should we have a way to catch changes from OverlayPlugin and raise an issue here? Is that feasible? Is it infrequent enough not to worry about?
> 
> I'm not sure there's an effective way to check for something like this. We'd have to somehow have an action here that triggers when an OP commit is merged, which I don't think exists?

Hmm, I know xp yoinks all our timeline updates from here and autogenerates a PR for his project to ingest them, I think he just uses a cron job to pull on a schedule though.

**Comment by valarnin** [comment]
> If a merge meeting those criteria is detected, we'd probably want to -- I guess, create an issue here to say "hey someone, go check this out". (That's probably the easiest part - a bunch of existing workflow actions for that we can hook.)

It would be just the `OverlayPlugin.Core/MemoryProcessors/Combatant/Common.cs` file that needs checked for updates/changes. Specifically the `Combatant` and `EffectEntry` classes in that file. This theoretical cron could use similar logic to the `StripFFXIVClientStructs` project on the OP side to parse the file out and check for more specific changes. It could even do a direct check if e.g. the `PluginCombatantState` cactbot-side exactly matches up in definition to what's on the OP side (fields missing from one and not the other, or data types differ). But I think that further discussion about this would be better on a new issue or in a future PR if someone wants to work on it.

**Pull request merged**
