### PR TITLE
docs: Add `ActorControlSelfExtra`

### LINKED ISSUE #118: Update resources & documentation for `ActorControlSelfExtra` lines
### Feature(s) Requested

Resources and documentation need to be updated for the new `ActorControlSelfExtra` lines added to OverlayPlugin in https://github.com/OverlayPlugin/OverlayPlugin/pull/329.

### PR DESCRIPTION
**Pull request by valarnin**
Running `generate-log-guide` picked up previous changes from #107, hence the regex changes for `CombatantMemory`.

Closes #118.

Wasn't sure if it made sense to flag other fields as `playerIds`, since technically any `param#` field could contain a player ID. This also holds true for `ActorControlExtra`.

### CODE REVIEW

**Comment by xiashtra** [comment]
I see that the `ActorControlExtra` categories were also expanded to include `DisplayPublicContentTextMessage`, do you have an example line/other information we can add to that section of the log guide?

**Comment by wexxlee** [comment]
> Wasn't sure if it made sense to flag other fields as `playerIds`, since technically any `param#` field could contain a player ID. This also holds true for `ActorControlExtra`.

Yeah, unfortunately, anonymizer doesn't support conditionally anonymizing a field that might contain a player id based on some other field value; it'll either throw an error if it expects but doesn't find a playerId-looking value in a `playerId` field, or it will throw an error if it finds a known player id in an unexpected field.

I *think* the second outcome is better for now (which is as you have it), so at least the person doing the anonymizing will get notified if a known player id is not getting anonymized in the exported log.  But we should probably add a TODO to have anonymizer support conditionally anonymizing fields without throwing errors.  (And if we're going to do that, we should probably also have it pre-populate `anonMap` with `AddedCombatant` player ids, rather than waiting until it encounters one in the wild.)

**Comment by valarnin** [comment]
> I see that the `ActorControlExtra` categories were also expanded to include `DisplayPublicContentTextMessage`, do you have an example line/other information we can add to that section of the log guide?

I don't have one saved that I wouldn't have to grep through 20gb of log files to find as a raw packet dump and then reconstruct, unfortunately.

I can add details for the params but not an example line.

**Comment by wexxlee** [comment]
> I don't have one saved that I wouldn't have to grep through 20gb of log files to find as a raw packet dump and then reconstruct, unfortunately.

I dug this up from #99 - should be reformattable if we want an example:
```
4096|2024-03-18T20:33:22.7130000-04:00|ActorControl|400058CA|2100|00000000|00000848|00000FA0|00000000|00000000|c862c35712ed4122
00|2024-03-18T20:33:22.0000000-04:00|0044|Art|O spear unyielding, become thee a thousand soldiers!|cf0c282daa64b90b
```

> 0x848 = https://xivapi.com/PublicContentTextData/2120

**Comment by valarnin** [comment]
Alright, added info about `DisplayPublicContentTextMessage`. Enabling auto-merge on this one since I won't have time to look at anything github-related tomorrow.

**Review by wexxlee — APPROVED** [review]

**Pull request merged**
