### PR TITLE
raidboss: remove remaining outdated dungeon files

### PR DESCRIPTION
**Pull request by xiashtra**
Continuation of quisquous/cactbot#5964: removes the remaining outdated dungeon files for pre-Trust updated dungeons.  Several instances still need to have their triggers/timelines function checked per #150.

### CODE REVIEW

**Review by wexxlee — COMMENTED** [review]
The corresponding synthetic ids/zone info in `util/zone_overrides.ts` should be removed, and  `gen_zone_id_and_info` should be re-run to yoink them out of the resource files.  But that script won't run properly right now due to the xivapi schema change to `TerritoryType`.  If you want to wait until #178 is merged, you could add to this PR and do it all at once.  Or would you rather land this now and do a follow-up PR after #178 lands?

**Comment by xiashtra** [comment]
> The corresponding synthetic ids/zone info in `util/zone_overrides.ts` should be removed

I thought we were keeping the synthetic IDs on purpose like we did with the Unreals just in-case there's references to the old IDs?

> But that script won't run properly right now due to the xivapi schema change to `TerritoryType`

What's the hold-up on their end?  The schema has been updated since last night.

**Comment by wexxlee** [comment]
> > The corresponding synthetic ids/zone info in `util/zone_overrides.ts` should be removed
> 
> I thought we were keeping the synthetic IDs on purpose like we did with the Unreals just in-case there's references to the old IDs?

We keep the synthetic IDs for old unreals because we also keep triggers/timelines for that content (which, maybe we don't need to do, but it's what we've done).  So there needs to be a valid zoneId for those files; once we remove timelines/triggers, we no longer need to keep the synthetic zone info.  I guess we don't technically need to remove them?  But it's basically just clutter at that point.

> > But that script won't run properly right now due to the xivapi schema change to `TerritoryType`
> 
> What's the hold-up on their end? The schema has been updated since last night.

Schema is updated, but `TerritoryIntendedUse` went from being a field on `TerritoryType` to being a relation (`TerritoryType.TerritoryIntendedUse.ID`), which requires code fixes on our end.

As I'm thinking more about this, we actually still have stale synthetic info for all the reworked dungeons, not just the 6.4 ones, that should probably get cleaned out.  Probably worth doing as a separate PR, so I think this is good to land as-is, and we can just add the clean-up to our to-do list (unless you disagree and think we should keep the synthetic stuff around?).

**Review by wexxlee — APPROVED** [review]

**Comment by xiashtra** [comment]
> > > The corresponding synthetic ids/zone info in `util/zone_overrides.ts` should be removed
> > 
> > 
> > I thought we were keeping the synthetic IDs on purpose like we did with the Unreals just in-case there's references to the old IDs?
> 
> We keep the synthetic IDs for old unreals because we also keep triggers/timelines for that content (which, maybe we don't need to do, but it's what we've done). So there needs to be a valid zoneId for those files; once we remove timelines/triggers, we no longer need to keep the synthetic zone info. I guess we don't technically need to remove them? But it's basically just clutter at that point.
> 
> > > But that script won't run properly right now due to the xivapi schema change to `TerritoryType`
> > 
> > 
> > What's the hold-up on their end? The schema has been updated since last night.
> 
> Schema is updated, but `TerritoryIntendedUse` went from being a field on `TerritoryType` to being a relation (`TerritoryType.TerritoryIntendedUse.ID`), which requires code fixes on our end (already included in #178).
> 
> As I'm thinking more about this, we actually still have stale synthetic info for all the reworked dungeons, not just the 6.4 ones, that should probably get cleaned out. Probably worth doing as a separate PR, so I think this is good to land as-is, and we can just add the clean-up to our to-do list (unless you disagree and think we should keep the synthetic stuff around?).

We left the dungeon synthetics when @quisquous merged the last set of removals, but if we really don't have any reason to keep them it would probably be just as well to remove them, though we do have some references in some of the guides to them (for how to set up synthetic zones) that should get cleaned up too if we do that.

**Comment by wexxlee** [comment]
> We left the dungeon synthetics when [@]quisquous merged the last set of removals, but if we really don't have any reason to keep them it would probably be just as well to remove them, though we do have some references in some of the guides to them (for how to set up synthetic zones) that should get cleaned up too if we do that.

I know the reworks are done for now, but there might be future scenarios where we do want to keep at least some reference to how to handle synthetic zones.  I'll just drop a TODO in the synthetic file, and we can revisit at some point (that's not 6 hours before a new expac 🙃)

**Pull request merged**
