### PR TITLE
i18n: add r4s cn translate

### PR DESCRIPTION
**Pull request by YuzukiTsuru**
In chinese, when using the Outputs defined will got:

- `靠近 => 靠近引导（小队远离）` : `In => Baits Close (Party Far)`
- `远离 => 靠近引导（小队靠近）`: `Out => Baits Far (Party Close)`

This can be confusing, so I'll use a custom output instead.

### CODE REVIEW

**Comment by wexxlee** [comment]
@YuzukiTsuru Do you want to add timeline translations too?

**Comment by ShadyWhite** [comment]
> @YuzukiTsuru Do you want to add timeline translations too?

Timeline translations cannot be added because the CN server has not yet been updated to 7.0.

**Comment by YuzukiTsuru** [comment]
> @YuzukiTsuru Do you want to add timeline translations too?

At present, the CN has not been launched DT yet, 2024.9.27 which is version 7.0 for CN server. So after updating the client, I will synchronize the timeline translation.

**Comment by wexxlee** [comment]
Ah, makes sense, thanks!

**Review by wexxlee — APPROVED** [review]

**Pull request merged**
